# Use an official Python runtime as a parent image
FROM python:3.10-slim-bullseye

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements file into the container
COPY ./requirements.txt /app/requirements.txt

# Install gcc and other dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libgl1 \
    libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

COPY ./models /app/models
COPY ./nu /app/data
# Copy your client script into the container
COPY ./client.py /app/client.py
COPY ./models.py /app/models.py
COPY ./load_data.py /app/load_data.py
COPY ./config.yaml /app/config.yaml
# Copy your server script into the container
COPY ./client.py /app/client.py
COPY ./base_training.py /app/base_training.py

# Specify the command to run the server script
ENTRYPOINT ["python", "base_training.py"]

