server: "127.0.0.1:8080"
rounds: 100
start_clients: 64
min_clients: 64
available_clients: 64
fraction_fit: 1.0
batch_size: 32
learning_rate: 0.1
epochs: 5
docker: true
working_dir: "/home/ubuntu/data/carla"
strategy: 
  name: "FedAvg"
classifier: "TinyClassifier"
model_checkpoint: False    
