server: "127.0.0.1:8080"
rounds: 10
start_clients: 2
min_clients: 2
available_clients: 2
fraction_fit: 1.0
batch_size: 32
learning_rate: 0.1
epochs: 2
docker: true
working_dir: "/home/ubuntu/data/carla"
strategy: 
  name: "FedAvgMDefault"
  params:
    server_learning_rate: 0.5
    server_momentum: 0.5