apiVersion: batch/v1
kind: Job
metadata:
  name: base-training
spec:
  template:
    metadata:
      labels:
        app: base-training
    spec:
      containers:
      - name: client
        image: ccsaba99/base-image:latest  # Replace with your Docker image
        env:
        volumeMounts:
        - mountPath: "/app/logs"  # Path inside the container where the volume will be mounted
          name: storage-volume          
      restartPolicy: Never  # Ensures the Job does not restart after completion
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: my-nfs-pvc  # Name of the PVC defined above      
  backoffLimit: 0  # Prevent retries on failure