# Use an official Python runtime as a parent image
FROM python:3.10-slim-bullseye

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements file into the container
COPY ./requirements.txt /app/requirements.txt

# Install gcc and other dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt


# Copy your server script into the container
COPY ./client.py /app/client.py
COPY ./server.py /app/server.py
COPY ./config.yaml /app/config.yaml
COPY ./strategies.py /app/strategies.py
COPY ./nu /app/data
# Specify the command to run the server script
ENTRYPOINT ["python", "server.py"]

