# Use an official Python runtime as a parent image
FROM python:3.10-slim-bullseye

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements file into the container
COPY ./requirements.txt /app/requirements.txt

# Install gcc and other dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

COPY ./nu/labels.csv /app/data/
COPY ./nu_cache/ /app/cache/
# Copy your server script into the container
COPY ./client.py /app/client.py
COPY ./server.py /app/server.py
COPY ./strategies.py /app/strategies.py
COPY ./models.py /app/models.py
COPY ./load_data.py /app/load_data.py
COPY ./models /app/models
COPY ./config.yaml /app/config.yaml
# Specify the command to run the server script
ENTRYPOINT ["python", "server.py"]

