# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements file into the container
COPY ./requirements.txt /app/requirements.txt

# Install gcc and other dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the Carla dataset files into the container
# COPY ./carla /app/carla
# COPY ./films_dataset/120-180-posters /app/films/images
# COPY ./films_dataset/genres/labels /app/films/labels

# Copy your client script into the container
COPY ./client_carla.py /app/client_carla.py
COPY ./config.yaml /app/config.yaml

# Create an entrypoint script
COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Specify the command to run the entrypoint script
ENTRYPOINT ["/app/entrypoint.sh"]

