server: "server:8080"
rounds: 10
start_clients: 32
min_clients: 32
available_clients: 32
fraction_fit: 1.0
batch_size: 32
learning_rate: 0.001
epochs: 2
docker: true
working_dir: "/home/ubuntu/data/carla"
strategy: 
  name: "FedCM"
  params:
    eta: 0.001
    eta_l: 0.001
    epoch_l: 3
    decay_alfa: 0.9