server: "server:8080"
rounds: 10
start_clients: 32
min_clients: 32
available_clients: 32
fraction_fit: 1.0
batch_size: 32
learning_rate: 0.0005
epochs: 2
docker: true
working_dir: "/home/ubuntu/data/carla"
strategy: 
  name: "FedAdamDefault"
  params:
    eta: 0.1
    eta_l: 0.1
    beta_1: 0.9
    beta_2: 0.9
    tau: 0.00000001