server: "server:8080"
rounds: 150
start_clients: 32
min_clients: 32
available_clients: 32
fraction_fit: 1.0
batch_size: 32
learning_rate: 0.001
epochs: 2
docker: true
working_dir: "/home/ubuntu/data/carla"
strategy:
  name: "FedAdam"
  params:
    eta: 0.001         # smaller server LR for stability
    eta_l: 0.001       # local LR
    beta_1: 0.9
    beta_2: 0.999      # stronger 2nd moment smoothing
    tau: 0.001          # larger damping
classifier: "TinyClassifier"